export const boardMembers = [
  {
    id: 1,
    name: 'Dr. Arif AlNooryani',
    role: 'Club Director',
    title: 'Consultant Cardiologist',
    department: 'Al Qassimi Hospital – EHS',
    initials: 'AN',
    photo: '/board/dr-arif-DHe2RV11.webp',
    bio: 'Leading the Al Qassimi Cardiology Club with a vision to advance cardiovascular care and education across the UAE.',
    row: 1,
  },
  {
    id: 2,
    name: 'Dr. Ehab ALSaeidy',
    role: 'Club Secretary',
    title: 'Specialist Cardiologist',
    department: 'Al Qassimi Hospital – EHS',
    initials: 'ES',
    photo: '/board/dr-ehab-al-saidy-JUsh0xJi.webp',
    bio: 'Coordinating club activities, scientific programs, and member communications to ensure seamless operations.',
    row: 2,
  },
  {
    id: 3,
    name: 'Dr. Wael Abo Shokka',
    role: 'Club Manager',
    title: 'Specialist Cardiologist',
    department: 'Al Qassimi Hospital – EHS',
    initials: 'WS',
    photo: '/board/dr-wael-aboushokka-LCB5-28J.webp',
    bio: 'Managing day-to-day club operations, logistics, and strategic partnerships with healthcare institutions.',
    row: 2,
  },
]
