export const waves = [
  {
    id: 1,
    title: 'Wave 1',
    date: 'April 24, 2025',
    dateShort: 'APR 24',
    poweredBy: 'AMGEN',
    chairperson: 'Dr. Georgios Sianos',
    timezone: 'UTC+4',
    sessions: [
      {
        id: 1,
        timeStart: '06:00 PM',
        timeEnd: '06:05 PM',
        topic: 'Opening',
        speaker: null,
        type: 'ceremony',
      },
      {
        id: 2,
        timeStart: '06:05 PM',
        timeEnd: '06:30 PM',
        topic: 'Every Delay Counts: When LDL-C Management Falls Short',
        speaker: 'Dr. Jalal Kerfes',
        type: 'lecture',
      },
      {
        id: 3,
        timeStart: '06:30 PM',
        timeEnd: '06:55 PM',
        topic: 'Addressing Residual Risk: Act Early, Treat Intensively, Prevent the Next Event',
        speaker: 'Dr. Hosam Zaki',
        type: 'lecture',
      },
      {
        id: 4,
        timeStart: '06:55 PM',
        timeEnd: '07:20 PM',
        topic: 'A New Pathway Forward: Protecting Patients at High Risk For a First CV Event',
        speaker: 'Dr. Paolo Fiorina',
        type: 'lecture',
      },
      {
        id: 5,
        timeStart: '07:20 PM',
        timeEnd: '07:45 PM',
        topic: 'Timing Matters: Improving Outcomes in Practice',
        speaker: 'Dr. Noha Yasin',
        type: 'lecture',
      },
      {
        id: 6,
        timeStart: '07:45 PM',
        timeEnd: '08:00 PM',
        topic: 'Q&A',
        speaker: null,
        type: 'qa',
      },
    ],
  },
]
